import { GoogleGenAI } from "@google/genai";
import { GenerationSettings, ENVIRONMENTS, VIBES } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export const generateFashionImage = async (
  base64Image: string,
  mimeType: string,
  settings: GenerationSettings
): Promise<string> => {
  const environmentPrompt = ENVIRONMENTS.find(e => e.id === settings.environment)?.prompt || settings.environment;
  const vibePrompt = VIBES.find(v => v.id === settings.vibe)?.prompt || settings.vibe;

  // Aesthetic refinement logic
  let ethnicityDesc = settings.ethnicity;
  let aestheticEnhancer = "";

  // Specifically target Chinese/Eastern beauty standards if 'asian' or 'diverse' is selected
  if (settings.ethnicity === 'asian' || settings.ethnicity === 'diverse') {
      ethnicityDesc = "East Asian female supermodel (Chinese aesthetic)";
      aestheticEnhancer = "exquisite facial features, delicate makeup, trending on Xiaohongshu, soft elegant temperament, fair skin, realistic skin texture, pore details";
  } else {
      aestheticEnhancer = "highly detailed skin texture, professional model, symmetrical face, vogue features";
  }

  const systemPrompt = `
    You are a world-class commercial fashion photographer. Your goal is to create a PHOTO-REALISTIC masterpiece.
    
    TASK:
    Generate a professional fashion photo of a model wearing the garment provided in the image.
    
    INPUT ANALYSIS:
    - Strictly observe the clothing item in the input image (cut, fabric, texture, pattern, logo).
    - Maintain the exact identity of the clothing.
    
    MODEL SPECIFICATION:
    - Subject: ${ethnicityDesc} ${settings.gender}.
    - Features: ${aestheticEnhancer}.
    - The model must look like a real person, not a 3D render or illustration.
    
    SCENE & STYLE:
    - Environment: ${environmentPrompt}.
    - Vibe: ${vibePrompt}.
    - Clothing Type: ${settings.clothingType}.
    
    TECHNICAL PHOTOGRAPHY GUIDELINES (CRITICAL):
    - Camera: Shot on Sony A7R IV or Fujifilm GFX 100.
    - Lens: 85mm f/1.8 (for portrait depth of field).
    - Quality: 8k UHD, RAW photo, sharp focus, high fidelity.
    - Lighting: Global illumination, ray tracing, natural light falloff, realistic shadows.
    
    NEGATIVE CONSTRAINTS (DO NOT DO):
    - NO anime, NO cartoon, NO illustration, NO 3D render style, NO oil painting style.
    - NO deformed hands, NO distorted face, NO bad anatomy.
    - NO fake plastic skin.
    
    Ensure the image looks like a high-end commercial advertisement for a luxury brand.
  `;

  // Retry logic loop
  const maxRetries = 3;
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              text: systemPrompt,
            },
            {
              inlineData: {
                data: base64Image,
                mimeType: mimeType,
              },
            },
          ],
        },
        config: {
          imageConfig: {
              aspectRatio: "3:4", 
          },
        }
      });

      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
      
      throw new Error("No image generated by the model.");

    } catch (error: any) {
      console.error(`Gemini API Attempt ${attempt} failed:`, error);
      
      // If it's the last attempt, or if it's not a server error (e.g. 400), throw immediately
      if (attempt === maxRetries || (error.status && error.status < 500 && error.status !== 429)) {
        throw error;
      }
      
      // Exponential backoff: 1s, 2s, 4s...
      await wait(1000 * Math.pow(2, attempt - 1));
    }
  }

  throw new Error("Failed to generate image after multiple attempts.");
};